### ISSUE TITLE
Get UnicodeDecodeError when there are Chinese characters in settings.ini

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/uliweb3#14]
Example settings:
```
(env3) zhangclb@zhangclb3:~/sandbox/timezone/timezonetest$ cat apps/local_settings.ini 
[GLOBAL]
DEBUG = True
DEBUG_CONSOLE = True
DEBUG_TEMPLATE = False

#TIME_ZONE = "UTC"
TIME_ZONE = "GMT +6"

TEST = "中文测试"
```
When default encoding is not utf8, will get error:
```
(env3) zhangclb@zhangclb3:~/sandbox/timezone/timezonetest$ export LANG=C
(env3) zhangclb@zhangclb3:~/sandbox/timezone/timezonetest$ uliweb runserver
Traceback (most recent call last):
  File "/home/zhangclb/.local/env3/bin/uliweb", line 11, in <module>
    load_entry_point('Uliweb3', 'console_scripts', 'uliweb')()
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 1604, in main
    call()
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 1601, in call
    execute_command_line(args or sys.argv, get_commands, 'uliweb', callback)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 417, in execute_command_line
    m.execute(callback)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 353, in execute
    self.do_command(args, global_options)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 380, in do_command
    command = self.fetch_command(global_options, subcommand)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 298, in fetch_command
    commands = self.get_commands(global_options)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 273, in get_commands
    commands = self.commands(global_options)
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 44, in get_commands
    collect_commands()
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 35, in collect_commands
    local_settings_file=global_options.local_settings)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/SimpleFrame.py", line 498, in get_apps
    x = pyini.Ini(local_inifile, basepath=apps_dir)
  File "/home/zhangclb/oss/uliweb3/uliweb/utils/pyini.py", line 442, in __init__
    self.read(self._inifile)
  File "/home/zhangclb/oss/uliweb3/uliweb/utils/pyini.py", line 479, in read
    text = f.read()
  File "/home/zhangclb/.local/env3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 116: ordinal not in range(128)
```

**Comment by limodou** [comment]
At top of file add `#coding=utf8`

**Comment by zhangchunlin** [comment]
> At top of file add `#coding=utf8`

not work:
```
(env3) zhangclb@zhangclb3:~/sandbox/timezone/timezonetest$ cat apps/local_settings.ini 
#coding=utf8

[GLOBAL]
DEBUG = True
DEBUG_CONSOLE = True
DEBUG_TEMPLATE = False

#TIME_ZONE = "UTC"
TIME_ZONE = "GMT +6"

TEST = "中文测试"
(env3) zhangclb@zhangclb3:~/sandbox/timezone/timezonetest$ export LANG=C
(env3) zhangclb@zhangclb3:~/sandbox/timezone/timezonetest$ uliweb runserver
Traceback (most recent call last):
  File "/home/zhangclb/.local/env3/bin/uliweb", line 11, in <module>
    load_entry_point('Uliweb3', 'console_scripts', 'uliweb')()
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 1604, in main
    call()
```

**Comment by zhangchunlin** [comment]
fixed in https://github.com/limodou/uliweb3/pull/15
