### ISSUE TITLE
get ModuleNotFoundError: No module named 'SocketServer' in windows

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/uliweb3#24]
```
zhangclb@ZHANGCLB-400158 MINGW64 /e/t/uliweb-apijson/demo (master)
$ uliweb runserver
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\uliweb\lib\werkzeug\serving.py", line 53, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\uliweb.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\uliweb\manage.py", line 1604, in main
    call()
  File "c:\python37\lib\site-packages\uliweb\manage.py", line 1601, in call
    execute_command_line(args or sys.argv, get_commands, 'uliweb', callback)
  File "c:\python37\lib\site-packages\uliweb\core\commands.py", line 417, in execute_command_line
    m.execute(callback)
  File "c:\python37\lib\site-packages\uliweb\core\commands.py", line 353, in execute
    self.do_command(args, global_options)
  File "c:\python37\lib\site-packages\uliweb\core\commands.py", line 386, in do_command
    cmd.run_from_argv(self.prog_name, subcommand, global_options, args[1:])
  File "c:\python37\lib\site-packages\uliweb\core\commands.py", line 192, in run_from_argv
    self.execute(args, options, global_options)
  File "c:\python37\lib\site-packages\uliweb\core\commands.py", line 214, in execute
    self.handle(options, global_options, *args)
  File "c:\python37\lib\site-packages\uliweb\manage.py", line 905, in handle
    self.run_simple(options, extra_files, get_app)
  File "c:\python37\lib\site-packages\uliweb\manage.py", line 1021, in run_simple
    from werkzeug.serving import run_simple
  File "c:\python37\lib\site-packages\uliweb\lib\werkzeug\serving.py", line 56, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn' from 'socketserver' (c:\python37\lib\socketserver.py)
```

**Comment by zhangchunlin** [comment]
There is a bug report of werkzeug: https://github.com/pallets/werkzeug/pull/999
And a fix: https://github.com/pallets/werkzeug/pull/999/commits/21672e84213e32a48131b6099dad7a1dfa675d30

**Comment by gddg** [comment]
PS D:\pyhome\Flask-SocketIO> pip install Werkzeug --upgrade
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting Werkzeug
  Downloading http://mirrors.aliyun.com/pypi/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl (327kB)
     |████████████████████████████████| 327kB 3.2MB/s
Installing collected packages: Werkzeug
Successfully installed Werkzeug-0.15.4
PS D:\pyhome\Flask-SocketIO> pipenv run

**Comment by zhangchunlin** [comment]
Hi, @gddg uliweb uses a modified Werkzeug, I think @limodou are working on it when he have time, it is long term solution, my patch might be a short term solution.

**Comment by zhangchunlin** [comment]
pull request was merged.
