### ISSUE TITLE
python3.7 uliweb3 error for "No module named  'SocketServer'"

### ISSUE THREAD

**Issue by cncg51** [limodou/uliweb3#32]
test the first step

$ uliweb runserver
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\uliweb\lib\werkzeug\serving.py", line 53, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'

**Comment by cncg51** [comment]
$ uliweb runserver
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\uliweb\lib\werkzeug\serving.py", line 53, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ModuleNotFoundError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python37\Scripts\uliweb.exe\__main__.py", line 9, in <module>
  File "d:\python37\lib\site-packages\uliweb\manage.py", line 1604, in main
    call()
  File "d:\python37\lib\site-packages\uliweb\manage.py", line 1601, in call
    execute_command_line(args or sys.argv, get_commands, 'uliweb', callback)
  File "d:\python37\lib\site-packages\uliweb\core\commands.py", line 417, in execute_command_line
    m.execute(callback)
  File "d:\python37\lib\site-packages\uliweb\core\commands.py", line 353, in execute
    self.do_command(args, global_options)
  File "d:\python37\lib\site-packages\uliweb\core\commands.py", line 386, in do_command
    cmd.run_from_argv(self.prog_name, subcommand, global_options, args[1:])
  File "d:\python37\lib\site-packages\uliweb\core\commands.py", line 192, in run_from_argv
    self.execute(args, options, global_options)
  File "d:\python37\lib\site-packages\uliweb\core\commands.py", line 214, in execute
    self.handle(options, global_options, *args)
  File "d:\python37\lib\site-packages\uliweb\manage.py", line 905, in handle
    self.run_simple(options, extra_files, get_app)
  File "d:\python37\lib\site-packages\uliweb\manage.py", line 1021, in run_simple
    from werkzeug.serving import run_simple
  File "d:\python37\lib\site-packages\uliweb\lib\werkzeug\serving.py", line 56, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn' from 'socketserver' (d:\python37\lib\socketserver.py)

**Comment by cncg51** [comment]
Thanks， Problem solved

**Comment by Bilal-Khan15** [comment]
I got the same problem, which was resolved by uninstalling and installing the Flask and Werkzeug again

1) pip uninstall Flask
2) pip uninstall Werkzeug

3) pip install Flask
4) pip install Werkzeug
