### ISSUE TITLE
latest sqlalchemy will get error: sqlalchemy.exc.ArgumentError: unknown strategy: 'threadlocal'

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/uliweb3#47]
```
Traceback (most recent call last):
  File "/home/zhangclb/sandbox/uliweb/env3/bin/uliweb", line 33, in <module>
    sys.exit(load_entry_point('Uliweb3', 'console_scripts', 'uliweb')())
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 1619, in main
    call()
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 1616, in call
    execute_command_line(args or sys.argv, get_commands, 'uliweb', callback)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 417, in execute_command_line
    m.execute(callback)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 353, in execute
    self.do_command(args, global_options)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 386, in do_command
    cmd.run_from_argv(self.prog_name, subcommand, global_options, args[1:])
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 192, in run_from_argv
    self.execute(args, options, global_options)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/commands.py", line 214, in execute
    self.handle(options, global_options, *args)
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 920, in handle
    self.run_simple(options, extra_files, get_app)
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 1054, in run_simple
    run_simple(options.hostname, options.port, get_app(), options.reload, False, True,
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 900, in get_app
    trace_print=options.trace_print)
  File "/home/zhangclb/oss/uliweb3/uliweb/manage.py", line 133, in make_application
    **dispatcher_kwargs)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/SimpleFrame.py", line 676, in __init__
    self.init(project_dir, apps_dir)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/SimpleFrame.py", line 724, in init
    dispatch.call(self, 'after_init_apps')
  File "/home/zhangclb/oss/uliweb3/uliweb/core/dispatch.py", line 110, in call
    _f(sender, *args, **kw)
  File "/home/zhangclb/oss/uliweb3/uliweb/contrib/orm/__init__.py", line 41, in after_init_apps
    orm.engine_manager.add('default', d)
  File "/home/zhangclb/oss/uliweb3/uliweb/orm/__init__.py", line 296, in add
    self.engines[name] = engine = NamedEngine(name, connection_args)
  File "/home/zhangclb/oss/uliweb3/uliweb/orm/__init__.py", line 245, in __init__
    self._create()
  File "/home/zhangclb/oss/uliweb3/uliweb/orm/__init__.py", line 261, in _create
    self.engine_instance = create_engine(c.get('connection_string'), **args)
  File "<string>", line 2, in create_engine
  File "/home/zhangclb/sandbox/uliweb/env3/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/zhangclb/sandbox/uliweb/env3/lib/python3.6/site-packages/sqlalchemy/engine/create.py", line 513, in create_engine
    raise exc.ArgumentError("unknown strategy: %r" % strat)
sqlalchemy.exc.ArgumentError: unknown strategy: 'threadlocal'
```

**Comment by zhangchunlin** [comment]
Links: [Using the Threadlocal Execution Strategy](https://docs.sqlalchemy.org/en/13/core/connections.html#using-the-threadlocal-execution-strategy) and [“threadlocal” engine strategy deprecated](https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#change-4393-threadlocal)
cc @limodou

**Comment by bullhe4d** [comment]
same issue,how to fix this problems?
