### ISSUE TITLE
use functions.get_model and give error

### ISSUE THREAD

**Issue by a740122** [limodou/uliweb3#54]
github version aa4aa0a
python version 3.7

```
def apps_manage_init():
    import os, sys
    from uliweb.manage import make_application
    path = os.path.dirname(os.path.abspath(__file__))
    if path not in sys.path:
        sys.path.insert(0, path)
    apps_dir = os.path.join(path, 'apps')
    application = make_application(apps_dir=apps_dir)
    from uliweb import functions
    from uliweb import manage
    
    manage.call('uliweb syncdb')

    functions.get_model
    return 
if __name__ == '__main__':
    r1 = apps_manage_init()
```

```
Traceback (most recent call last):
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\utils\pyini.py", line 600, in read
    v = eval_value(value, self.env(), self[sec_name], self._encoding, self._import_env)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\utils\pyini.py", line 201, in eval_value
    result = eval(txt, dict(globals), dict(locals))
  File "<string>", line 1
    #coding=UTF-8
                ^
SyntaxError: unexpected EOF while parsing
Traceback (most recent call last):
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\utils\pyini.py", line 600, in read
    v = eval_value(value, self.env(), self[sec_name], self._encoding, self._import_env)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\utils\pyini.py", line 201, in eval_value
    result = eval(txt, dict(globals), dict(locals))
  File "<string>", line 1
    #coding=UTF-8
                ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps_manager.py", line 21, in <module>
    r1 = apps_manage_init()
  File "apps_manager.py", line 9, in apps_manage_init
    application = make_application(apps_dir=apps_dir)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\manage.py", line 133, in make_application
    **dispatcher_kwargs)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\core\SimpleFrame.py", line 677, in __init__
    self.init(project_dir, apps_dir)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\core\SimpleFrame.py", line 690, in init
    Dispatcher.apps = get_apps(self.apps_dir, self.include_apps, self.settings_file, self.local_settings_file)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\core\SimpleFrame.py", line 498, in get_apps
    x = pyini.Ini(inifile, basepath=apps_dir)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\utils\pyini.py", line 442, in __init__
    self.read(self._inifile)
  File "D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\uliweb\utils\pyini.py", line 603, in read
    raise Exception("Converting value (%s) error in %s:%d:%s" % (value, filename or self._inifile, lineno, line))
Exception: Converting value () error in D:\Dev\python\venv\0000_Case\Carpark01\Carpark01-py37\Carpark01_proj\apps\settings.ini:2:DEBUG = True
```

**Comment by limodou** [comment]
Please use py3.9, I test it is ok
