### ISSUE TITLE
AttributeError: 'Expose' object has no attribute '__name__'

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/uliweb3#58]
Acutally it is a test case in test_expose.py, it also can be reproduced with this code:
```
from uliweb import expose

@expose
class A:
    @expose
    def index(self, id):
        pass

print(A)
```
Run this code will get the error:
```
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb3/test_expose.py", line 3, in <module>
    @expose
  File "/home/zhangclb/oss/uliweb3/uliweb/core/SimpleFrame.py", line 278, in expose
    e = rules.Expose(rule, **kwargs)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 144, in __init__
    self.parse(rule)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 217, in parse
    self.parse_class(f)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 290, in parse_class
    rule = self._get_url(appname, prefix, func)
  File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 313, in _get_url
    if f.__name__ in reserved_keys:
AttributeError: 'Expose' object has no attribute '__name__'
```

**Comment by limodou** [comment]
Just like #59
