### ISSUE TITLE
AttributeError: 'method' object has no attribute '__exposed__'

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/uliweb3#59]
After 4bb0ebaf538104b3a374e7ac58fe3944caf1c2e6, get a new error in test:
```
File "/home/zhangclb/oss/uliweb3/test/test_expose.py", line 68, in test
Failed example:
    @expose
    class A:
        def index(self, id):pass
        @classmethod
        def p(cls, id):pass
        @staticmethod
        def x(id):pass
Exception raised:
    Traceback (most recent call last):
      File "/home/zhangclb/.pyenv/versions/3.6.5/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest test[30]>", line 1, in <module>
        @expose
      File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 127, in expose
        e = Expose(rule, **kwargs)
      File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 144, in __init__
        self.parse(rule)
      File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 216, in parse
        self.parse_class(f)
      File "/home/zhangclb/oss/uliweb3/uliweb/core/rules.py", line 296, in parse_class
        setattr(func, '__exposed__', True)
    AttributeError: 'method' object has no attribute '__exposed__'
```

**Comment by limodou** [comment]
The test case is not suit for py3, so just remove it.
